services:
  openalgo:
    container_name: openalgo${BROKER:+_${BROKER}}
    image: openalgo${BROKER:+_${BROKER}}:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${FLASK_PORT:-5005}:5000"
      - "${WEBSOCKET_PORT:-8765}:8765"

    # persistent DB, logs + mount the host .env read-only so dotenv can read it
    volumes:
      # Use named volume for database to avoid SQLite locking issues on Windows
      - openalgo_db:/app/db
      - ./logs:/app/logs
      - ./.env${BROKER:+_${BROKER}}:/app/.env:ro   # ← .env stays on your machine

    # (optional) extra env-vars that are NOT in .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}

    restart: unless-stopped

# Define named volumes for database persistence
volumes:
  openalgo_db:
    driver: local
